#!/usr/bin/env node
/* eslint-disable no-console */
//
// Build the bundle if missing, gzip the ESM output, and report its
// size. Writes the result to SIZE.md so the DoD's 50 KB cap can be
// checked in CI.

const fs = require("node:fs");
const path = require("node:path");
const zlib = require("node:zlib");
const { execSync } = require("node:child_process");

const root = path.resolve(__dirname, "..");
const dist = path.join(root, "dist", "index.mjs");

if (!fs.existsSync(dist)) {
  execSync("pnpm build", { cwd: root, stdio: "inherit" });
}

const raw = fs.readFileSync(dist);
const gz = zlib.gzipSync(raw, { level: 9 });

const rawKb = (raw.byteLength / 1024).toFixed(2);
const gzKb = (gz.byteLength / 1024).toFixed(2);
const cap = 50.0;

const body = [
  `# Bundle size (ESM, gzip level 9)`,
  ``,
  `| Metric            | Bytes              | KB     |`,
  `| ----------------- | ------------------ | ------ |`,
  `| raw \`index.mjs\` | ${raw.byteLength}  | ${rawKb} |`,
  `| gzipped           | ${gz.byteLength}   | ${gzKb}  |`,
  ``,
  `DoD cap: ${cap} KB gzipped.`,
  ``,
  `Generated by \`pnpm size\`.`,
].join("\n");

fs.writeFileSync(path.join(root, "SIZE.md"), body + "\n");
console.log(body);

if (parseFloat(gzKb) > cap) {
  console.error(`\nbundle exceeds ${cap} KB cap (${gzKb} KB)`);
  process.exit(1);
}
