#!/usr/bin/env node
/* eslint-disable no-console */
//
// Convert a snarkjs proof.json + public.json pair into the JSON
// fixture shape the contracts sandbox tests load.
//
// Usage:
//   node scripts/proof_to_fixture.js \
//     [proof.json] [public.json] [out_fixture.json]
//
// Defaults look in circuits/build/.

const fs = require("node:fs");
const path = require("node:path");
const { bls12_381 } = require("@noble/curves/bls12-381");

const proofPath  = process.argv[2] ?? path.join(__dirname, "..", "build", "proof.json");
const publicPath = process.argv[3] ?? path.join(__dirname, "..", "build", "public.json");
const outPath    = process.argv[4] ?? path.join(__dirname, "..", "..", "contracts", "tests", "fixtures", "phase_a_accept.json");

const proof  = JSON.parse(fs.readFileSync(proofPath, "utf8"));
const pubVec = JSON.parse(fs.readFileSync(publicPath, "utf8"));

const G1 = bls12_381.G1.ProjectivePoint;
const G2 = bls12_381.G2.ProjectivePoint;
const Fp = bls12_381.fields.Fp;
const Fp2 = bls12_381.fields.Fp2;

function g1FromSnarkjs(arr) {
  const x = BigInt(arr[0]);
  const y = BigInt(arr[1]);
  const z = BigInt(arr[2]);
  if (z !== 1n) throw new Error(`expected Z=1, got ${z}`);
  return G1.fromAffine({ x: Fp.create(x), y: Fp.create(y) });
}

function g2FromSnarkjs(arr) {
  const x = { c0: BigInt(arr[0][0]), c1: BigInt(arr[0][1]) };
  const y = { c0: BigInt(arr[1][0]), c1: BigInt(arr[1][1]) };
  const z = { c0: BigInt(arr[2][0]), c1: BigInt(arr[2][1]) };
  if (z.c0 !== 1n || z.c1 !== 0n) {
    throw new Error(`expected projective Z=(1,0), got (${z.c0}, ${z.c1})`);
  }
  return G2.fromAffine({ x: Fp2.create(x), y: Fp2.create(y) });
}

function toHexUpper(bytes) {
  return Buffer.from(bytes).toString("hex").toUpperCase();
}

const A = g1FromSnarkjs(proof.pi_a);
const B = g2FromSnarkjs(proof.pi_b);
const C = g1FromSnarkjs(proof.pi_c);

const fixture = {
  _comment:
    "Generated by circuits/scripts/proof_to_fixture.js. Real Groth16 proof produced by the v0.2 Phase-A circuit + ceremony.",
  protocol: proof.protocol,
  curve: proof.curve,
  aHex: toHexUpper(A.toRawBytes(true)),
  bHex: toHexUpper(B.toRawBytes(true)),
  cHex: toHexUpper(C.toRawBytes(true)),
  publicInputs: pubVec,
};

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, JSON.stringify(fixture, null, 2) + "\n");
console.error(`wrote ${path.relative(process.cwd(), outPath)} (${fixture.aHex.length / 2}B A + ${fixture.bHex.length / 2}B B + ${fixture.cHex.length / 2}B C, ${pubVec.length} public)`);
