#!/usr/bin/env node
/* eslint-disable no-console */
//
// Reads circuits/account_age/verification_key.json and emits FunC
// helper functions returning the VK constants as slices, ready to
// paste into contracts/verifier/groth16_verifier.fc.
//
// Usage:
//   node scripts/vk_to_func.js [path/to/verification_key.json]

const fs = require("node:fs");
const path = require("node:path");
const { bls12_381 } = require("@noble/curves/bls12-381");

const vkPath =
  process.argv[2] ?? path.join(__dirname, "..", "account_age", "verification_key.json");
const vk = JSON.parse(fs.readFileSync(vkPath, "utf8"));

if (vk.curve !== "bls12381") {
  throw new Error(`expected curve=bls12381, got ${vk.curve}`);
}
if (vk.protocol !== "groth16") {
  throw new Error(`expected protocol=groth16, got ${vk.protocol}`);
}

const G1 = bls12_381.G1.ProjectivePoint;
const G2 = bls12_381.G2.ProjectivePoint;
const Fp = bls12_381.fields.Fp;
const Fp2 = bls12_381.fields.Fp2;

// snarkjs writes points as [x, y, z] decimal strings in projective form.
// Z is 0 for the point-at-infinity, 1 for affine.
function g1FromSnarkjs(arr) {
  const x = BigInt(arr[0]);
  const y = BigInt(arr[1]);
  const z = BigInt(arr[2]);
  if (z !== 1n) throw new Error(`expected projective Z=1, got ${z}`);
  return G1.fromAffine({ x: Fp.create(x), y: Fp.create(y) });
}

function g2FromSnarkjs(arr) {
  // arr = [[x0, x1], [y0, y1], [z0, z1]]
  const x = { c0: BigInt(arr[0][0]), c1: BigInt(arr[0][1]) };
  const y = { c0: BigInt(arr[1][0]), c1: BigInt(arr[1][1]) };
  const z = { c0: BigInt(arr[2][0]), c1: BigInt(arr[2][1]) };
  if (z.c0 !== 1n || z.c1 !== 0n) {
    throw new Error(`expected projective Z=(1,0), got (${z.c0}, ${z.c1})`);
  }
  return G2.fromAffine({ x: Fp2.create(x), y: Fp2.create(y) });
}

function toCompressedHex(point) {
  // Both G1.toRawBytes and G2.toRawBytes return IETF-compressed bytes
  // (48 bytes for G1, 96 bytes for G2). Same encoding TON expects.
  return Buffer.from(point.toRawBytes(true)).toString("hex").toUpperCase();
}

function emitG1(name, point) {
  const h = toCompressedHex(point);
  if (h.length !== 96) throw new Error(`G1 hex length ${h.length}, expected 96`);
  const c1 = h.slice(0, 48);
  const c2 = h.slice(48);
  return `slice ${name}() inline {
    return begin_cell()
        .store_uint(0x${c1}, 192)
        .store_uint(0x${c2}, 192)
        .end_cell().begin_parse();
}`;
}

function emitG2(name, point) {
  const h = toCompressedHex(point);
  if (h.length !== 192) throw new Error(`G2 hex length ${h.length}, expected 192`);
  const cs = [];
  for (let i = 0; i < 192; i += 48) cs.push(h.slice(i, i + 48));
  const lines = cs.map((c) => `        .store_uint(0x${c}, 192)`).join("\n");
  return `slice ${name}() inline {
    return begin_cell()
${lines}
        .end_cell().begin_parse();
}`;
}

const alpha = g1FromSnarkjs(vk.vk_alpha_1);
const beta = g2FromSnarkjs(vk.vk_beta_2);
const gamma = g2FromSnarkjs(vk.vk_gamma_2);
const delta = g2FromSnarkjs(vk.vk_delta_2);
const ic = vk.IC.map(g1FromSnarkjs);

console.log("// generated by scripts/vk_to_func.js — do not edit by hand");
console.log("// source:", path.relative(process.cwd(), vkPath));
console.log();
console.log(emitG1("vk_alpha_g1", alpha));
console.log();
console.log(emitG2("vk_beta_g2", beta));
console.log();
console.log(emitG2("vk_gamma_g2", gamma));
console.log();
console.log(emitG2("vk_delta_g2", delta));
console.log();
for (let i = 0; i < ic.length; i++) {
  console.log(emitG1(`vk_ic_${i}`, ic[i]));
  console.log();
}

console.error(`emitted ${4 + ic.length} VK accessors (IC count=${ic.length})`);
